import json
from tools.github_tool import get_repo_info
from tools.weather_tool import get_weather

TOOL_MAP = {
    "github_tool": get_repo_info,
    "weather_tool": get_weather
}

def execute_plan(plan: dict) -> dict:
    """
    Executes the plan generated by the Planner Agent.
    
    Args:
        plan (dict): The JSON plan containing 'steps'.
        
    Returns:
        dict: A dictionary of results for each step.
    """
    results = {}
    with open("last_plan.json", "w") as f:
        json.dump(plan, f, indent=2)
    steps = plan.get("steps", [])
    
    if not steps:
        return {"error": "No steps found in plan."}
        
    for i, step in enumerate(steps):
        tool_name = step.get("tool_name")
        arguments = step.get("arguments", {})
        description = step.get("step_description")
        
        print(f"Executing Step {i+1}: {description}")
        
        if tool_name in TOOL_MAP:
            tool_func = TOOL_MAP[tool_name]
            try:
                # Call the tool with unpacked arguments
                result = tool_func(**arguments)
                results[f"step_{i+1}"] = {
                    "tool": tool_name,
                    "description": description,
                    "output": result
                }
            except Exception as e:
                results[f"step_{i+1}"] = {
                    "tool": tool_name,
                    "error": str(e)
                }
        else:
            results[f"step_{i+1}"] = {
                "tool": tool_name,
                "error": f"Tool '{tool_name}' not found."
            }
            
    return results
